import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/Components/Footer";
import Navbar from '@/Components/Navbar'

export const metadata: Metadata = {
  title: "Landing Page ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="relative overflow-hidden">
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
